export const THEMES = {
  '8-bit-sheep': require('jsonresume-theme-8-bit-sheep'),
  a11y: require('jsonresume-theme-a11y'),
  aboutcontent: require('jsonresume-theme-aboutcontent'),
  ace: require('jsonresume-theme-ace'),
  actual: require('jsonresume-theme-actual'),
  'actual-letter': require('jsonresume-theme-actual-letter'),
  apage: require('jsonresume-theme-apage'),
  autumn: require('jsonresume-theme-autumn'),
  'autumn-custom': require('jsonresume-theme-autumn-custom'),
  'autumn-pathify': require('jsonresume-theme-autumn-pathify'),
  boilerplate: require('jsonresume-theme-boilerplate'),
  'boilerplate-vforesee': require('jsonresume-theme-boilerplate-vforesee'),
  boldstatement: require('jsonresume-theme-boldstatement'),
  briefstrap: require('jsonresume-theme-briefstrap'),
  'business-professional-compact': require('jsonresume-theme-business-professional-compact'),
  caffeine: require('jsonresume-theme-caffeine'),
  class: require('jsonresume-theme-class'),
  'class-vforesee': require('jsonresume-theme-class-vforesee'),
  classy: require('jsonresume-theme-classy'),
  coffee: require('jsonresume-theme-coffee'),
  compact: require('jsonresume-theme-compact'),
  'compact-extended': require('jsonresume-theme-compact-extended'),
  'compact-new': require('jsonresume-theme-compact-new'),
  'compact-pt-br': require('jsonresume-theme-compact-pt-br'),
  compactbr: require('jsonresume-theme-compactbr'),
  contempo: require('jsonresume-theme-contempo'),
  'contempo-vforesee': require('jsonresume-theme-contempo-vforesee'),
  cora: require('jsonresume-theme-cora'),
  curzy: require('jsonresume-theme-curzy'),
  cvstrap: require('jsonresume-theme-cvstrap'),
  'dark-classy': require('jsonresume-theme-dark-classy'),
  'dark-classy-responsive': require('jsonresume-theme-dark-classy-responsive'),
  daru: require('jsonresume-theme-daru'),
  'daru-new': require('jsonresume-theme-daru-new'),
  dave: require('jsonresume-theme-dave'),
  debordementdepile: require('jsonresume-theme-debordementdepile'),
  developpez: require('jsonresume-theme-developpez'),
  dinesh: require('jsonresume-theme-dinesh'),
  direct: require('jsonresume-theme-direct'),
  'el-santo': require('jsonresume-theme-el-santo'),
  elegant: require('jsonresume-theme-elegant'),
  'elegant-custom': require('jsonresume-theme-elegant-custom'),
  'elegant-fr': require('jsonresume-theme-elegant-fr'),
  'elegant-fr-mod': require('jsonresume-theme-elegant-fr-mod'),
  'elegant-fr2': require('jsonresume-theme-elegant-fr2'),
  'elegant-jali': require('jsonresume-theme-elegant-jali'),
  'elegant-leonth': require('jsonresume-theme-elegant-leonth'),
  'elegant-maksymgendin': require('jsonresume-theme-elegant-maksymgendin'),
  'elegant-mobile': require('jsonresume-theme-elegant-mobile'),
  'elegant-mrseanryan': require('jsonresume-theme-elegant-mrseanryan'),
  'elegant-projects': require('jsonresume-theme-elegant-projects'),
  'elegant-tw': require('jsonresume-theme-elegant-tw'),
  'elegant-zh-hant': require('jsonresume-theme-elegant-zh-hant'),
  eleganter: require('jsonresume-theme-eleganter'),
  elegantfixed: require('jsonresume-theme-elegantfixed'),
  elegantnew: require('jsonresume-theme-elegantnew'),
  elephant: require('jsonresume-theme-elephant'),
  elite: require('jsonresume-theme-elite'),
  eloquent: require('jsonresume-theme-eloquent'),
  'eloquent-mod': require('jsonresume-theme-eloquent-mod'),
  'eloquent-ru': require('jsonresume-theme-eloquent-ru'),
  'eternal-de': require('jsonresume-theme-eternal-de'),
  even: require('jsonresume-theme-even'),
  'even-gdpr': require('jsonresume-theme-even-gdpr'),
  flat: require('jsonresume-theme-flat'),
  'flat-fr': require('jsonresume-theme-flat-fr'),
  'flat-optimized': require('jsonresume-theme-flat-optimized'),
  'flat-projects': require('jsonresume-theme-flat-projects'),
  'flat-revised': require('jsonresume-theme-flat-revised'),
  foxyboxy: require('jsonresume-theme-foxyboxy'),
  fresh: require('jsonresume-theme-fresh'),
  'fresh-certificate': require('jsonresume-theme-fresh-certificate'),
  'fresh-vforesee': require('jsonresume-theme-fresh-vforesee'),
  full: require('jsonresume-theme-full'),
  'full-ext': require('jsonresume-theme-full-ext'),
  fullmoon: require('jsonresume-theme-fullmoon'),
  github: require('jsonresume-theme-github'),
  'github-vforesee': require('jsonresume-theme-github-vforesee'),
  gnap: require('jsonresume-theme-gnap'),
  hexagon: require('jsonresume-theme-hexagon'),
  hired: require('jsonresume-theme-hired'),
  hydejack: require('jsonresume-theme-hydejack'),
  jacrys: require('jsonresume-theme-jacrys'),
  jdambron: require('jsonresume-theme-jdambron'),
  'jdambron-fr': require('jsonresume-theme-jdambron-fr'),
  joeytall: require('jsonresume-theme-joeytall'),
  jupe: require('jsonresume-theme-jupe'),
  kards: require('jsonresume-theme-kards'),
  kate: require('jsonresume-theme-kate'),
  kcv: require('jsonresume-theme-kcv'),
  keloran: require('jsonresume-theme-keloran'),
  'keloran-fr': require('jsonresume-theme-keloran-fr'),
  kendall: require('jsonresume-theme-kendall'),
  'kendall-felipecrs': require('jsonresume-theme-kendall-felipecrs'),
  'kendall-german': require('jsonresume-theme-kendall-german'),
  'kendall-herink': require('jsonresume-theme-kendall-herink'),
  'kendall-ksenia': require('jsonresume-theme-kendall-ksenia'),
  'kendall-modern': require('jsonresume-theme-kendall-modern'),
  'kendall-plus': require('jsonresume-theme-kendall-plus'),
  'kendall-projects': require('jsonresume-theme-kendall-projects'),
  'kendall-vforesee': require('jsonresume-theme-kendall-vforesee'),
  kindrobot: require('jsonresume-theme-kindrobot'),
  'kwan-linkedin': require('jsonresume-theme-kwan-linkedin'),
  latex: require('jsonresume-theme-latex'),
  lemonlabs: require('jsonresume-theme-lemonlabs'),
  'light-classy-concise': require('jsonresume-theme-light-classy-concise'),
  'light-classy-responsive': require('jsonresume-theme-light-classy-responsive'),
  'light-classy-responsive-m2': require('jsonresume-theme-light-classy-responsive-m2'),
  lowmess: require('jsonresume-theme-lowmess'),
  lukemeads: require('jsonresume-theme-lukemeads'),
  macchiato: require('jsonresume-theme-macchiato'),
  'macchiato-ibic': require('jsonresume-theme-macchiato-ibic'),
  'macchiato-macea': require('jsonresume-theme-macchiato-macea'),
  macea: require('jsonresume-theme-macea'),
  'macea-ece': require('jsonresume-theme-macea-ece'),
  mantra: require('jsonresume-theme-mantra'),
  markdown: require('jsonresume-theme-markdown'),
  material: require('jsonresume-theme-material'),
  'material-moon': require('jsonresume-theme-material-moon'),
  md: require('jsonresume-theme-md'),
  'mocha-responsive': require('jsonresume-theme-mocha-responsive'),
  modern: require('jsonresume-theme-modern'),
  moon: require('jsonresume-theme-moon'),
  mooser: require('jsonresume-theme-mooser'),
  msresume: require('jsonresume-theme-msresume'),
  'nl-flat': require('jsonresume-theme-nl-flat'),
  one: require('jsonresume-theme-one'),
  onepage: require('jsonresume-theme-onepage'),
  'onepage-plus': require('jsonresume-theme-onepage-plus'),
  'onepage-simplified': require('jsonresume-theme-onepage-simplified'),
  'onepage-updated': require('jsonresume-theme-onepage-updated'),
  onepageresume: require('jsonresume-theme-onepageresume'),
  orbit: require('jsonresume-theme-orbit'),
  'orbit-original': require('jsonresume-theme-orbit-original'),
  'orbit-remasterized-fr': require('jsonresume-theme-orbit-remasterized-fr'),
  'orbit-vforesee': require('jsonresume-theme-orbit-vforesee'),
  paper: require('jsonresume-theme-paper'),
  'paper-plus-plus': require('jsonresume-theme-paper-plus-plus'),
  'paper-vforesee': require('jsonresume-theme-paper-vforesee'),
  'paper-w-certs': require('jsonresume-theme-paper-w-certs'),
  'paper-zh-hant': require('jsonresume-theme-paper-zh-hant'),
  paper_cn: require('jsonresume-theme-paper_cn'),
  paperalt: require('jsonresume-theme-paperalt'),
  papirus: require('jsonresume-theme-papirus'),
  pillar: require('jsonresume-theme-pillar'),
  polymer: require('jsonresume-theme-polymer'),
  'print-flexbox': require('jsonresume-theme-print-flexbox'),
  printclassy: require('jsonresume-theme-printclassy'),
  pumpkin: require('jsonresume-theme-pumpkin'),
  qlh: require('jsonresume-theme-qlh'),
  ravgift: require('jsonresume-theme-ravgift'),
  resu: require('jsonresume-theme-resu'),
  rickosborne: require('jsonresume-theme-rickosborne'),
  riga: require('jsonresume-theme-riga'),
  rnord: require('jsonresume-theme-rnord'),
  rocketspacer: require('jsonresume-theme-rocketspacer'),
  'rocketspacer-vforesee': require('jsonresume-theme-rocketspacer-vforesee'),
  samk: require('jsonresume-theme-samk'),
  sceptile: require('jsonresume-theme-sceptile'),
  sfy: require('jsonresume-theme-sfy'),
  short: require('jsonresume-theme-short'),
  'short-extended': require('jsonresume-theme-short-extended'),
  'shorter-miles': require('jsonresume-theme-shorter-miles'),
  simple: require('jsonresume-theme-simple'),
  'simple-red': require('jsonresume-theme-simple-red'),
  simplyelegant: require('jsonresume-theme-simplyelegant'),
  skills: require('jsonresume-theme-skills'),
  slick: require('jsonresume-theme-slick'),
  slickoverflow: require('jsonresume-theme-slickoverflow'),
  smart: require('jsonresume-theme-smart'),
  'so-moon': require('jsonresume-theme-so-moon'),
  spartacus: require('jsonresume-theme-spartacus'),
  'spartacus-nl': require('jsonresume-theme-spartacus-nl'),
  'spartacus-prime': require('jsonresume-theme-spartacus-prime'),
  spartan: require('jsonresume-theme-spartan'),
  'spartan-extended': require('jsonresume-theme-spartan-extended'),
  'spartan-extended-certs': require('jsonresume-theme-spartan-extended-certs'),
  srt: require('jsonresume-theme-srt'),
  'srt-vforesee': require('jsonresume-theme-srt-vforesee'),
  'srt-wide': require('jsonresume-theme-srt-wide'),
  stackoverflow: require('jsonresume-theme-stackoverflow'),
  'stackoverflow-detailed': require('jsonresume-theme-stackoverflow-detailed'),
  'stackoverflow-es': require('jsonresume-theme-stackoverflow-es'),
  'stackoverflow-fr': require('jsonresume-theme-stackoverflow-fr'),
  'stackoverflow-ibic': require('jsonresume-theme-stackoverflow-ibic'),
  'stackoverflow-marion': require('jsonresume-theme-stackoverflow-marion'),
  'stackoverflow-mats': require('jsonresume-theme-stackoverflow-mats'),
  'stackoverflow-plus': require('jsonresume-theme-stackoverflow-plus'),
  'stackoverflow-react': require('jsonresume-theme-stackoverflow-react'),
  'stackoverflow-skills': require('jsonresume-theme-stackoverflow-skills'),
  'stackoverflow-skills-below-education': require('jsonresume-theme-stackoverflow-skills-below-education'),
  'stackoverflow-vforesee': require('jsonresume-theme-stackoverflow-vforesee'),
  stackoverflow2: require('jsonresume-theme-stackoverflow2'),
  stackoverflowed: require('jsonresume-theme-stackoverflowed'),
  stackunderflow: require('jsonresume-theme-stackunderflow'),
  standard: require('jsonresume-theme-standard'),
  'standard-resume': require('jsonresume-theme-standard-resume'),
  'standard-resume-de': require('jsonresume-theme-standard-resume-de'),
  'standard-resume-extended': require('jsonresume-theme-standard-resume-extended'),
  'standard-resume-vforesee': require('jsonresume-theme-standard-resume-vforesee'),
  straightforward: require('jsonresume-theme-straightforward'),
  'straightforward-certs': require('jsonresume-theme-straightforward-certs'),
  'tachyons-clean': require('jsonresume-theme-tachyons-clean'),
  'tan-responsive': require('jsonresume-theme-tan-responsive'),
  techlead: require('jsonresume-theme-techlead'),
  test: require('jsonresume-theme-test'),
  'timeline-fixed': require('jsonresume-theme-timeline-fixed'),
  umennel: require('jsonresume-theme-umennel'),
  verbum: require('jsonresume-theme-verbum'),
  waterfall: require('jsonresume-theme-waterfall'),
  wraypro: require('jsonresume-theme-wraypro'),
  zurb: require('jsonresume-theme-zurb'),
  'jsonresume-themes-feed': require('jsonresume-themes-feed'),
  'jsonresume-themeutils': require('jsonresume-themeutils'),
};

const getTheme = (theme) => {
  try {
    return THEMES[theme];
  } catch (e) {
    return {
      e: e.toString(),
      error: 'Theme is not supported.',
    };
  }
};

const format = async function (resume, options) {
  const theme = options.theme ?? 'elegant';
  const themeRenderer = getTheme(theme);
  const resumeHTML = themeRenderer.render(resume);

  return {
    content: resumeHTML,
    headers: [
      {
        key: 'Cache-control',
        value: 'public, max-age=90',
      },
      {
        key: 'Content-Type',
        value: 'text/html',
      },
    ],
  };
};

export default { format };
