name: Auto Generate Blog Post

on:
  schedule:
    # Run every 2 weeks on Sunday at 10am UTC
    - cron: '0 10 */14 * 0'
  workflow_dispatch: # Allow manual trigger

jobs:
  generate-blog-post:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Install dependencies
      run: |
        cd apps/homepage
        npm install
        
    - name: Generate blog post
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: |
        cd apps/homepage
        node scripts/generate-blog-post.js
        
    - name: Build blog
      run: |
        cd apps/homepage
        npm run build
        
    - name: Commit and push if changed
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if ! git diff-index --quiet HEAD; then
          git commit -m "Auto-generated blog post

          Generated based on GitHub activity from the past 2 weeks.
          
          🤖 Generated with GitHub Actions"
          git push
        else
          echo "No changes to commit"
        fi